import { StyleSheet } from "react-native";
import {
    getDangerColor,
    getPrimary2ndColor,
    getPrimaryColor,
    getSecondary2ndColor,
    getSecondaryColor,
    getSuccessColor,
    getWhiteColor,
} from "./Colors";

export const globalStyles = StyleSheet.create({
    container: {
        padding: 16,
        paddingBottom: 0,
        backgroundColor: getPrimary2ndColor(),
    },
    containerCard: {
        flex: 1,
        backgroundColor: getPrimary2ndColor(),
    },
    profileCard: {
        marginVertical: 8,
        marginHorizontal: 16,
        padding: 20,
        borderRadius: 10,
        backgroundColor: getWhiteColor(),
        shadowColor: getPrimaryColor(),
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    card: {
        flexDirection: "row",
        gap: 12,
        marginVertical: 8,
        padding: 12,
        margin: 16,
        borderRadius: 8,
        backgroundColor: getWhiteColor(),
        shadowColor: getPrimaryColor(),
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    title: {
        fontWeight: "bold",
        fontSize: 16,
        color: getPrimaryColor(),
    },
    image: {
        width: 64,
        height: 64,
        borderRadius: 8,
    },
    buttonText: {
        color: "white",
        textAlign: "center",
    },
    buttonPrimary: {
        backgroundColor: getPrimaryColor(),
        padding: 12,
        borderRadius: 8,
        marginTop: 12,
    },
    buttonSuccess: {
        backgroundColor: getSuccessColor(),
        padding: 12,
        borderRadius: 8,
        marginTop: 12,
    },
    buttonDanger: {
        backgroundColor: getDangerColor(),
        padding: 12,
        borderRadius: 8,
        marginTop: 12,
    },
    buttonSecondary: {
        backgroundColor: getSecondaryColor(),
        padding: 12,
        borderRadius: 8,
        marginTop: 12,
    },
    text: {
        fontSize: 16,
        marginBottom: 8,
        textAlign: "center",
    },
    emptyText: {
        textAlign: "center",
        marginTop: 16,
        fontStyle: "italic",
    },
    label: {
        marginTop: 12,
        marginBottom: 4,
        fontWeight: "bold",
    },
    input: {
        borderWidth: 1,
        borderColor: getSecondary2ndColor(),
        borderRadius: 8,
        padding: 8,
        backgroundColor: getWhiteColor(),
    },
    imagePreview: {
        width: 100,
        height: 100,
        borderRadius: 8,
        marginTop: 8,
    },
    stokRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginVertical: 15,
        gap: 10,
    },
    stokItem: {
        alignItems: "center",
        flex: 1,
        backgroundColor: getWhiteColor(),
        borderRadius: 8,
        padding: 10,
        shadowColor: getPrimaryColor(),
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    stokLabel: {
        fontWeight: "bold",
        fontSize: 14,
    },
    stokValue: {
        fontSize: 14,
        marginTop: 4,
    },
    homeCard: {
        marginBottom: 12,
        padding: 30,
        borderRadius: 8,
        backgroundColor: getPrimaryColor(),
        shadowColor: getPrimaryColor(),
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    homeCardHalfContainer: {
        flexDirection: "row",
        gap: 12,
    },
    homeCardHalf: {
        flex: 1,
        width: "50%",
        marginBottom: 12,
        padding: 20,
        borderRadius: 8,
        backgroundColor: getPrimaryColor(),
        shadowColor: getPrimaryColor(),
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    buttonModalPrimary: {
        backgroundColor: getPrimaryColor(),
        padding: 8,
        borderRadius: 6,
    },
    buttonModalSuccess: {
        backgroundColor: getSuccessColor(),
        padding: 8,
        borderRadius: 6,
    },
    buttonModalDanger: {
        backgroundColor: getDangerColor(),
        padding: 8,
        borderRadius: 6,
    },
    buttonModalSecondary: {
        backgroundColor: getSecondaryColor(),
        padding: 8,
        borderRadius: 6,
    },
    pickerRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 16,
    },
    picker: {
        height: 50,
        width: 100,
    },
    cardFull: {
        backgroundColor: getWhiteColor(),
        padding: 20,
        borderRadius: 12,
        marginBottom: 12,
        marginHorizontal: 15,
        elevation: 2,
        shadowColor: getPrimaryColor(),
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    rowCards: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginHorizontal: 15,
    },
    cardHalf: {
        flex: 0.48,
        backgroundColor: getWhiteColor(),
        padding: 20,
        borderRadius: 12,
        elevation: 2,
        shadowColor: getPrimaryColor(),
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    cardTitle: {
        fontSize: 16,
        marginBottom: 4,
    },
    cardValue: {
        fontSize: 20,
        fontWeight: "bold",
    },
});
