import { StyleSheet } from "react-native";

export const globalStyles = StyleSheet.create({
    container: {
        // flex: 1,
        padding: 16,
        paddingBottom: 0,
        backgroundColor: "#e3ecfcff",
    },
    containerCard: {
        flex: 1,
        backgroundColor: "#e3ecfcff",
    },
    card: {
        flexDirection: "row",
        gap: 12,
        marginVertical: 8,
        padding: 12,
        margin: 16,
        borderRadius: 8,
        backgroundColor: "#fff",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    title: {
        fontWeight: "bold",
        fontSize: 16,
    },
    image: {
        width: 64,
        height: 64,
        borderRadius: 8,
    },
    buttonText: {
        color: "white",
        textAlign: "center",
    },
    buttonPrimary: {
        backgroundColor: "#1e90ff",
        padding: 12,
        borderRadius: 8,
        marginTop: 12,
    },
    buttonSuccess: {
        backgroundColor: "#24953eff",
        padding: 12,
        borderRadius: 8,
        marginTop: 12,
    },
    buttonDanger: {
        backgroundColor: "#d43545ff",
        padding: 12,
        borderRadius: 8,
        marginTop: 12,
    },
    buttonSecondary: {
        backgroundColor: "#f2f2f2",
        padding: 12,
        borderRadius: 8,
        marginTop: 12,
    },
    text: {
        fontSize: 16,
        marginBottom: 8,
        textAlign: "center",
    },
    emptyText: {
        textAlign: "center",
        marginTop: 16,
        fontStyle: "italic",
    },
    label: {
        marginTop: 12,
        marginBottom: 4,
        fontWeight: "bold",
    },
    input: {
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 8,
        padding: 8,
        backgroundColor: "#fff",
    },
    imagePreview: {
        width: 100,
        height: 100,
        borderRadius: 8,
        marginTop: 8,
    },
    stokRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginVertical: 15,
        gap: 10,
    },
    stokItem: {
        alignItems: "center",
        flex: 1,
        backgroundColor: "#f2f2f2",
        borderRadius: 8,
        padding: 10,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    stokLabel: {
        fontWeight: "bold",
        fontSize: 14,
    },
    stokValue: {
        fontSize: 14,
        marginTop: 4,
    },
    homeCard: {
        marginBottom: 8,
        padding: 12,
        borderRadius: 8,
        backgroundColor: "#fff",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    homeCardHalfContainer: {
        flexDirection: "row",
        gap: 8,
    },
    homeCardHalf: {
        flex: 1,
        width: "50%",
        marginBottom: 8,
        padding: 12,
        borderRadius: 8,
        backgroundColor: "#fff",
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    buttonModalPrimary: {
        backgroundColor: "#1e90ff",
        padding: 8,
        borderRadius: 6,
    },
    buttonModalSuccess: {
        backgroundColor: "#24953eff",
        padding: 8,
        borderRadius: 6,
    },
    buttonModalDanger: {
        backgroundColor: "#d43545ff",
        padding: 8,
        borderRadius: 6,
    },
    buttonModalSecondary: {
        backgroundColor: "#f2f2f2",
        padding: 8,
        borderRadius: 6,
    },
    pickerRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginBottom: 16,
    },
    picker: {
        height: 50,
        width: 100,
    },
    cardFull: {
        backgroundColor: "#fff",
        padding: 20,
        borderRadius: 12,
        marginBottom: 12,
        marginHorizontal: 15,
        elevation: 2,
    },
    rowCards: {
        flexDirection: "row",
        justifyContent: "space-between",
        marginHorizontal: 15,
    },
    cardHalf: {
        flex: 0.48,
        backgroundColor: "#fff",
        padding: 20,
        borderRadius: 12,
        elevation: 2,
    },
    cardTitle: {
        fontSize: 16,
        color: "#333333",
        marginBottom: 4,
    },
    cardValue: {
        fontSize: 20,
        fontWeight: "bold",
        color: "#000",
    },
});
